name: '(shared functionality) Deploy'

on:
  workflow_call:
    inputs:
      TERRAFORM_STATE_BUCKET:
        required: true
        type: string
      TERRAFORM_STATE_FILE:
        required: true
        type: string
      TERRAFORM_TFVARS_FILE:
        required: true
        type: string
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID:
        required: true
      TERRAFORM_AWS_SECRET_ACCESS_KEY:
        required: true
      BASIC_AUTH_USERNAME:
        required: true
      BASIC_AUTH_PASSWORD:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    outputs:
      static_website_s3_bucket: ${{ steps.static_website_s3_bucket.outputs.test }}

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Init Terraform'
        run: |
          terraform init "-backend-config=bucket=${{ inputs.TERRAFORM_STATE_BUCKET }}" "-backend-config=key=${{ inputs.TERRAFORM_STATE_FILE }}" "-backend-config=region=${{ env.AWS_DEFAULT_REGION }}" "-backend-config=access_key=${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}" "-backend-config=secret_key=${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}"
        working-directory: ./terraform

      - name: 'Apply Terraform changes'
        run: |
          terraform apply \
          -var-file "${{ inputs.TERRAFORM_TFVARS_FILE }}" \
          -var "BASIC_AUTH_USERNAME=${{ secrets.BASIC_AUTH_USERNAME }}" \
          -var "BASIC_AUTH_PASSWORD=${{ secrets.BASIC_AUTH_PASSWORD }}" \
          -auto-approve
        working-directory: ./terraform

      - name: 'Download the TFState file'
        run: |
          aws s3 cp "s3://${{ inputs.TERRAFORM_STATE_BUCKET }}/${{ inputs.TERRAFORM_STATE_FILE }}" ./current_tf_state.json

      - id: static_website_s3_bucket
        name: 'Find the name of the S3 bucket where we will put the static website files'
        run: |
          echo test=$(jq -r '.resources[] | select(.name == "static_website_s3_bucket").instances[].attributes.bucket' current_tf_state.json) >> static_website_s3_bucket.txt
          cat static_website_s3_bucket.txt
          cat static_website_s3_bucket.txt >> $GITHUB_OUTPUT

  build_and_deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    needs: terraform

    env:
      GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"
      STATIC_WEBSITE_S3_BUCKET: "${{needs.terraform.outputs.static_website_s3_bucket}}"
      GITHUB_WORKING_DIR: "${{ github.workspace }}"

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: 'Install R'
        uses: r-lib/actions/setup-r@v2

      - name: 'Restore dependencies cache'
        uses: actions/cache/restore@v3
        with:
          path: "${{ env.R_LIBS_USER }}"
          key: "r-dependencies-v1"

      - name: 'Install Pandoc'
        uses: r-lib/actions/setup-pandoc@v2

      - name: 'Install apt-get packages'
        run: |
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev r-base

      - name: 'Install R packages'
        run: |
          Rscript -e 'install.packages(c("remotes", "kableExtra", "blogdown"))'

      - name: 'Install blogdown'
        run: |
          Rscript -e 'blogdown::install_hugo()'

      - name: 'Install GovUkHugo'
        run: |
          Rscript -e 'remotes::install_github("co-analysis/govuk-hugo-r")'

      - name: 'Save dependencies cache'
        uses: actions/cache/save@v3
        with:
          path: "${{ env.R_LIBS_USER }}"
          key: "r-dependencies-v1"

      - name: 'Build site using GovUkHugo'
        run: |
          Rscript -e 'govukhugo::build_hugo()'

      - name: 'Copy the files to AWS S3'
        run: |
          aws s3 sync . s3://${{ env.STATIC_WEBSITE_S3_BUCKET }} --delete --exclude '.git*'
        working-directory: ./public
